export interface PromptItem {
  id: string;
  brand: "Northline Coffee" | "Studio Nine";
  title: string;
  imagePrompt: string;
  caption: string;
  hashtags: string[];
  aspect: "4:5" | "1:1" | "16:9";
  model: "cloudflare-workers-ai" | "gemini-2.5-flash" | "dall-e-3";
  status: "queued" | "generating" | "ready" | "scheduled" | "posted" | "failed";
  estimatedCost: string;
}

export const SEED_PROMPTS: PromptItem[] = [
  {
    id: "nl-01",
    brand: "Northline Coffee",
    title: "Artisanal Pour-Over Ritual",
    imagePrompt: "Matte black ceramic dripper over clear glass carafe on textured soapstone counter, stream of golden amber coffee, morning natural side light, 4:5 vertical editorial photography.",
    caption: "Slow mornings call for deliberate rituals. Hand-poured Ethiopian Yirgacheffe notes of bergamot and jasmine now brewing at all roastery locations.",
    hashtags: ["#NorthlineCoffee", "#PourOverRitual", "#SpecialtyCoffee", "#CraftRoasters"],
    aspect: "4:5",
    model: "cloudflare-workers-ai",
    status: "ready",
    estimatedCost: "$0.03",
  },
  {
    id: "nl-02",
    brand: "Northline Coffee",
    title: "Cold Brew Extraction Process",
    imagePrompt: "Slow cold-drip tower with ice and dark rich concentrate in laboratory glassware, dramatic chiaroscuro lighting, minimalist studio setting.",
    caption: "Extracted for 18 hours at 4°C. Smooth chocolate undertones with zero acidity. Grab our ready-to-pour bottles in-store today.",
    hashtags: ["#ColdBrewCraft", "#NorthlineRoast", "#SingleOrigin", "#CoffeeLaboratory"],
    aspect: "1:1",
    model: "cloudflare-workers-ai",
    status: "scheduled",
    estimatedCost: "$0.03",
  },
  {
    id: "s9-01",
    brand: "Studio Nine",
    title: "Monochrome Modular Workspace",
    imagePrompt: "Brushed aluminum desk setup, mechanical keyboard, ultra-thin borderless monitor displaying code metrics, matte black concrete wall, soft directional backlight.",
    caption: "The environment shapes the output. Engineered for focus, zero distractions, and maximum developer flow.",
    hashtags: ["#StudioNine", "#WorkspaceDesign", "#MinimalDesk", "#IndustrialDesign"],
    aspect: "4:5",
    model: "cloudflare-workers-ai",
    status: "posted",
    estimatedCost: "$0.03",
  },
  {
    id: "s9-02",
    brand: "Studio Nine",
    title: "Sculptural Audio Hardware",
    imagePrompt: "Geometric matte white ceramic audio monitors on walnut acoustic risers, high contrast product photography, clean shadows.",
    caption: "Sound engineering meets minimalist form. Previewing the acoustic series arriving late autumn.",
    hashtags: ["#AcousticDesign", "#StudioNineGear", "#IndustrialAesthetics"],
    aspect: "16:9",
    model: "cloudflare-workers-ai",
    status: "generating",
    estimatedCost: "$0.03",
  },
  {
    id: "s9-03",
    brand: "Studio Nine",
    title: "Typography Specimen Poster",
    imagePrompt: "Swiss style typography poster pinned to raw graphite board, bold sans-serif numerals, ultra crisp macro photography, high sharpness.",
    caption: "Form follows precision. Print edition 04 is currently in pre-press.",
    hashtags: ["#TypographyDaily", "#SwissDesign", "#PrintCraft"],
    aspect: "4:5",
    model: "cloudflare-workers-ai",
    status: "queued",
    estimatedCost: "$0.03",
  },
  {
    id: "nl-03",
    brand: "Northline Coffee",
    title: "Seasonal Single-Origin Beans",
    imagePrompt: "Unroasted green coffee beans alongside roasted deep brown coffee beans on brushed brass testing tray, cupping spoon, editorial macro shot.",
    caption: "From farm gate to cupping table. The fresh harvest from Huila, Colombia has cleared quality control.",
    hashtags: ["#DirectTrade", "#NorthlineOrigin", "#CuppingTable"],
    aspect: "4:5",
    model: "cloudflare-workers-ai",
    status: "failed",
    estimatedCost: "$0.03",
  },
  {
    id: "ap-04",
    brand: "Studio Nine",
    title: "Distributed Systems Infrastructure Diagram",
    imagePrompt: "Isometric monochrome schematic diagram of serverless edge nodes, glowing hairline connection vectors, dark slate backdrop, high fidelity technical render.",
    caption: "Designing for 99.999% uptime requires thinking in distributed micro-clusters rather than monolithic relays.",
    hashtags: ["#SystemDesign", "#CloudInfrastructure", "#DevEngineering"],
    aspect: "16:9",
    model: "cloudflare-workers-ai",
    status: "ready",
    estimatedCost: "$0.03",
  },
  {
    id: "ap-05",
    brand: "Studio Nine",
    title: "Mechanical Keycap Macro Study",
    imagePrompt: "PBT double-shot keycaps on custom CNC brass plate, soft diffused overhead lighting, matte black anodized aluminum chamfer.",
    caption: "Every millimeter of tactile travel matters. The obsidian edition goes into prototype validation this Friday.",
    hashtags: ["#MechanicalKeyboards", "#IndustrialDesign", "#DeskSetup"],
    aspect: "1:1",
    model: "cloudflare-workers-ai",
    status: "ready",
    estimatedCost: "$0.03",
  },
  {
    id: "nl-04",
    brand: "Northline Coffee",
    title: "Espresso Puck Extraction Geometry",
    imagePrompt: "Bottomless portafilter extracting espresso with tiger striping crema into transparent double-walled glass, studio rim light.",
    caption: "Dialed to 1:2.1 ratio at 9 bars. Crisp notes of dark cocoa, candied orange peel, and dried stone fruit.",
    hashtags: ["#EspressoObsession", "#NorthlineRoasters", "#SpecialtyCoffee"],
    aspect: "4:5",
    model: "cloudflare-workers-ai",
    status: "scheduled",
    estimatedCost: "$0.03",
  },
  {
    id: "s9-06",
    brand: "Studio Nine",
    title: "Dark Mode Code Editor Interface",
    imagePrompt: "Sleek IDE workspace on Retina display with high contrast syntax highlighting, terminal output in JetBrains mono, ambient glow.",
    caption: "Low latency, instant feedback loops, zero cognitive friction. How our frontend team maintains velocity.",
    hashtags: ["#FrontendEngineering", "#DevTools", "#WebDev"],
    aspect: "4:5",
    model: "cloudflare-workers-ai",
    status: "queued",
    estimatedCost: "$0.03",
  },
];
