"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { CheckCircle2, Layers, ShieldCheck } from "lucide-react";
import { Stepper } from "@/_components/stepper";
import { OnboardingFooter } from "@/_components/onboarding-footer";
import { SETUP_STEPS } from "@/_lib/steps";
import { useToast } from "@/_components/ui/toast";

const STYLE_PRESETS = [
  { id: "Modern Minimalist", name: "Modern Minimalist", description: "Sharp architectural lines and natural daylight.", instruction: "Modern minimalist architectural photography, clean geometry, natural sunlight, photorealistic", tag: "POPULAR" },
  { id: "Cinematic Warm", name: "Cinematic Warm", description: "Golden light, atmosphere, and rich tactile texture.", instruction: "Cinematic architectural photography, golden hour lighting, rich textures, authentic environment", tag: "EDITORIAL" },
  { id: "Tropical Vernacular", name: "Tropical Modern", description: "Natural timber and lush greenery in open layouts.", instruction: "Contemporary tropical design photography, exposed timber, native landscaping, dramatic shadows", tag: "ORGANIC" },
  { id: "Studio Monochrome", name: "Studio Editorial", description: "Deep shadows and dramatic luxury composition.", instruction: "Luxury architectural editorial, dramatic directional lighting, bold monochrome tones", tag: "DEFAULT" },
];

export default function SetupPage() {
  const router = useRouter();
  const { addToast } = useToast();
  const [selectedStyle, setSelectedStyle] = useState(STYLE_PRESETS[0].id);
  const [isFinishing, setIsFinishing] = useState(false);

  const handleFinish = async () => {
    setIsFinishing(true);
    try {
      const chosenPreset = STYLE_PRESETS.find((style) => style.id === selectedStyle);
      await fetch("/api/settings", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ defaultStylePreset: chosenPreset?.instruction }),
      });
      addToast({ title: "Setup completed", description: "Cloudflare image generation is ready for your prompts.", variant: "success" });
    } finally {
      router.push("/dashboard");
      setIsFinishing(false);
    }
  };

  return (
    <>
      <div className="flex-1 max-w-6xl w-full mx-auto px-4 sm:px-6 py-8 sm:py-12">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          <aside className="lg:col-span-4 space-y-6">
            <div className="p-6 border border-border bg-surface rounded-xs shadow-xs space-y-6">
              <div>
                <span className="font-mono text-[10px] uppercase tracking-widest text-muted font-semibold">ONBOARDING // STAGE 02</span>
                <h2 className="text-headline-sm font-bold text-foreground mt-1">Image Generation Engine</h2>
                <p className="text-body-sm text-muted mt-1 leading-relaxed">Images are generated by the workspace Cloudflare Workers AI connection. No personal AI key is required.</p>
              </div>
              <Stepper steps={SETUP_STEPS} currentStep={2} variant="vertical" completedDescriptionOverride={{ 2: "Cloudflare Workers AI" }} />
            </div>
            <div className="p-5 border border-border bg-surface-strong rounded-xs space-y-2.5 font-mono text-xs">
              <div className="flex items-center gap-2 text-foreground font-semibold"><ShieldCheck size={16} className="text-accent-ready shrink-0" /><span>MANAGED INFERENCE</span></div>
              <p className="text-muted leading-relaxed">The workspace owner configures Cloudflare once. Your team never enters, stores, or shares an image-provider key.</p>
            </div>
          </aside>

          <section className="lg:col-span-8 p-6 sm:p-10 border border-border bg-surface rounded-xs shadow-xs space-y-8 font-mono">
            <div className="space-y-2">
              <span className="text-xs text-muted uppercase tracking-widest font-semibold">STEP 02 // STYLE</span>
              <h1 className="text-headline-xl font-bold text-foreground tracking-tight">Configure your visual direction</h1>
              <p className="text-body-md text-muted leading-relaxed">Choose the default style added to each prompt before it is sent to Cloudflare Workers AI.</p>
            </div>
            <div className="p-5 border border-border bg-surface-strong rounded-xs flex gap-3 text-xs text-muted">
              <CheckCircle2 size={18} className="text-accent-ready shrink-0" />
              <p><strong className="text-foreground">Cloudflare-managed image generation is enabled.</strong> No Gemini, OpenAI, or other personal-model credential is used.</p>
            </div>
            <div className="space-y-4">
              <div className="flex items-center gap-2"><Layers size={16} className="text-foreground" /><h3 className="text-xs uppercase font-bold tracking-wider text-foreground">Select default style preset</h3></div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5">
                {STYLE_PRESETS.map((preset) => {
                  const isSelected = selectedStyle === preset.id;
                  return <button key={preset.id} type="button" onClick={() => setSelectedStyle(preset.id)} aria-pressed={isSelected} className={`p-4 border rounded-xs text-left transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-foreground ${isSelected ? "border-foreground bg-surface-strong shadow-xs" : "border-border bg-surface hover:border-foreground/40"}`}>
                    <div className="flex items-center justify-between mb-1.5"><span className="font-bold text-xs text-foreground">{preset.name}</span><span className="text-[10px] px-1.5 py-0.5 border border-border rounded-xs text-muted">{preset.tag}</span></div>
                    <p className="text-[11px] text-muted leading-relaxed">{preset.description}</p>
                  </button>;
                })}
              </div>
            </div>
          </section>
        </div>
      </div>
      <OnboardingFooter backHref="/get-started/connect" onNext={handleFinish} isNextDisabled={isFinishing} nextLabel={isFinishing ? "Configuring..." : "Complete Setup & Launch Dashboard"} />
    </>
  );
}
