"use client";

import React from "react";
import {
  LayoutDashboard,
  Bookmark,
  Hourglass,
  CheckSquare,
  Calendar,
  Send,
  Settings,
  Check,
  CheckCircle2,
  X,
  Menu,
  ChevronRight,
  ChevronDown,
  ChevronLeft,
  ChevronUp,
  ArrowRight,
  ArrowLeft,
  Loader2,
  Sparkles,
  Info,
  Lock,
  Unlock,
  Shield,
  ShieldCheck,
  HelpCircle,
  Plus,
  Bell,
  Sliders,
  ExternalLink,
  Layers,
  FileText,
  Search,
  Trash2,
  Eye,
  EyeOff,
  Clock,
  BarChart3,
  RefreshCw,
  Copy,
  FolderPlus,
  Play,
  PlayCircle,
  Tag,
  MapPin,
  Smile,
  AlertTriangle,
  AlertCircle,
  Palette,
  Share2,
  Sun,
  Moon,
  type LucideIcon,
} from "lucide-react";

export interface IconProps {
  name: string;
  className?: string;
  size?: number;
  fill?: boolean;
}

// Comprehensive mapping from Material Symbol names to Lucide icons
const iconMap: Record<string, LucideIcon> = {
  // Navigation & Core
  space_dashboard: LayoutDashboard,
  dashboard: LayoutDashboard,
  collections_bookmark: Bookmark,
  bookmark: Bookmark,
  hourglass_top: Hourglass,
  hourglass: Hourglass,
  fact_check: CheckSquare,
  calendar_month: Calendar,
  calendar: Calendar,
  send: Send,
  settings: Settings,
  home: LayoutDashboard,

  // Actions & Controls
  check: Check,
  check_circle: CheckCircle2,
  close: X,
  x: X,
  menu: Menu,
  chevron_right: ChevronRight,
  chevron_down: ChevronDown,
  chevron_left: ChevronLeft,
  chevron_up: ChevronUp,
  expand_more: ChevronDown,
  keyboard_arrow_down: ChevronDown,
  arrow_forward: ArrowRight,
  arrow_back: ArrowLeft,
  arrow_right: ArrowRight,
  arrow_left: ArrowLeft,
  add: Plus,
  plus: Plus,
  trash: Trash2,
  delete: Trash2,
  refresh: RefreshCw,
  copy: Copy,
  search: Search,

  // Status & Notifications
  progress_activity: Loader2,
  loading: Loader2,
  spinner: Loader2,
  auto_awesome: Sparkles,
  sparkles: Sparkles,
  info: Info,
  lock: Lock,
  unlock: Unlock,
  verified: ShieldCheck,
  verified_user: ShieldCheck,
  shield: Shield,
  help_outline: HelpCircle,
  help: HelpCircle,
  notifications: Bell,
  bell: Bell,
  warning: AlertTriangle,
  error: AlertCircle,

  // Content & Features
  tune: Sliders,
  open_in_new: ExternalLink,
  external_link: ExternalLink,
  library_books: Layers,
  layers: Layers,
  edit_note: FileText,
  file: FileText,
  queue_play_next: Layers,
  insights: BarChart3,
  bar_chart: BarChart3,
  schedule: Clock,
  clock: Clock,
  folder_plus: FolderPlus,
  play: Play,
  play_circle: PlayCircle,
  tag: Tag,
  location_on: MapPin,
  sentiment_satisfied: Smile,
  palette: Palette,
  hub: Share2,
  eye: Eye,
  eye_off: EyeOff,
  sun: Sun,
  moon: Moon,

  // Fallbacks
  roofing: Layers,
};

export function Icon({ name, className = "", size = 18, fill = false }: IconProps) {
  const Component = iconMap[name.toLowerCase()] || Layers;
  return (
    <Component
      size={size}
      className={className}
      strokeWidth={1.75}
      fill={fill ? "currentColor" : "none"}
      aria-hidden="true"
    />
  );
}

export {
  LayoutDashboard,
  Bookmark,
  Hourglass,
  CheckSquare,
  Calendar,
  Send,
  Settings,
  Check,
  CheckCircle2,
  X,
  Menu,
  ChevronRight,
  ChevronDown,
  ChevronLeft,
  ArrowRight,
  ArrowLeft,
  Loader2,
  Sparkles,
  Info,
  Lock,
  Unlock,
  ShieldCheck,
  HelpCircle,
  Plus,
  Bell,
  Sliders,
  ExternalLink,
  Layers,
  FileText,
  Search,
  Trash2,
  Eye,
  EyeOff,
  Clock,
  BarChart3,
  RefreshCw,
  Copy,
  FolderPlus,
  Play,
  PlayCircle,
  Tag,
  MapPin,
  Smile,
  AlertTriangle,
  AlertCircle,
  Palette,
  Share2,
  Sun,
  Moon,
};
